--creearemos una tabla simple para probar pl sql 
CREATE TABLE DANCE(ID_DANCER integer, NOMBRE varchar2(40), EDAD integer);
--TENEMOS EL SERVIDOR EN MODO DE DESARROLLADOR.
--VAMOS A EMPEZAR CON UN BLOQUE PL SQL
SET SERVEROUTPUT ON;

-- SE DECLARA LAS VARIABLES
 DECLARE 
EDAD INTEGER;
YEARS INTEGER;

--AQUI VA LA LOGICA DEL PROGRAMA
BEGIN
YEARS:=21;
EDAD:=YEARS*365;
--IMPRIME EL RESULTADO
DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES: '||EDAD);
END;
/
